In [96]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
sns.set()

from sklearn.linear_model import LinearRegression

In [97]:
data = pd.read_csv(r"D:\Users\mathe\OneDrive\Documentos\Data Science\Dados\1.01.+Simple+linear+regression.csv")

In [98]:
x = data["SAT"]
y = data["GPA"]

In [99]:
x.shape # Uma dimensão

(84,)

In [100]:
x_matrix = x.values.reshape(-1,1) # Duas dimeções

In [101]:
x_matrix.shape

(84, 1)

In [102]:
y.shape

(84,)

In [103]:
reg = LinearRegression()

In [104]:
reg.fit(x_matrix,y) # x - inputs e y - target

LinearRegression()

In [105]:
# Encontrando o R2
reg.score(x_matrix,y)

0.40600391479679765

In [106]:
# Encontrando o coeficiente da variável (x)
reg.coef_

array([0.00165569])

In [107]:
# Encontrando o coeficiente da constante (y)
reg.intercept_

0.27504029966028076

In [108]:
x = np.array([1740]).reshape(-1, 1)
y_pred = reg.predict(x)
y_pred

array([3.15593751])

In [109]:
new_data = pd.DataFrame(data=[1740,1760], columns=["SAT"])
new_data

SAT
0  1740
1  1760

In [110]:
reg.predict(new_data)

c:\Users\Matheus\AppData\Local\Programs\Python\Python311\Lib\site-packages\sklearn\base.py:413: UserWarning: X has feature names, but LinearRegression was fitted without feature names
  warnings.warn(


array([3.15593751, 3.18905127])

In [111]:
new_data["Predicted_GPA"] = reg.predict(new_data)
new_data

c:\Users\Matheus\AppData\Local\Programs\Python\Python311\Lib\site-packages\sklearn\base.py:413: UserWarning: X has feature names, but LinearRegression was fitted without feature names
  warnings.warn(


SAT  Predicted_GPA
0  1740       3.155938
1  1760       3.189051