In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
sns.set()

from sklearn.linear_model import LinearRegression

In [2]:
data = pd.read_csv(r"D:\Users\mathe\OneDrive\Documentos\Data Science\Dados\real_estate_price_size.csv")

In [3]:
x = data["size"]
y = data["price"]

In [13]:
data.describe()

price         size
count     100.000000   100.000000
mean   292289.470160   853.024200
std     77051.727525   297.941951
min    154282.128000   479.750000
25%    234280.148000   643.330000
50%    280590.716000   696.405000
75%    335723.696000  1029.322500
max    500681.128000  1842.510000

In [4]:
x_matrix = x.values.reshape(-1,1)

In [5]:
reg = LinearRegression()

In [7]:
reg.fit(x_matrix,y)

LinearRegression()

In [8]:
reg.score(x_matrix,y)

0.7447391865847587

In [9]:
reg.coef_

array([223.17874259])

In [10]:
reg.intercept_

101912.60180122912

In [15]:
x = np.array([2000]).reshape(-1,1)
y_pred = reg.predict(x)
y_pred

array([548270.08699044])

In [16]:
new_data = pd.DataFrame(data = [1000, 2000], columns = ["Size(m2)"])
new_data

Size(m2)
0      1000
1      2000

In [17]:
reg.predict(new_data)

c:\Users\Matheus\AppData\Local\Programs\Python\Python311\Lib\site-packages\sklearn\base.py:413: UserWarning: X has feature names, but LinearRegression was fitted without feature names
  warnings.warn(


array([325091.34439584, 548270.08699044])

In [18]:
new_data["Predict_Price"] = reg.predict(new_data)
new_data

c:\Users\Matheus\AppData\Local\Programs\Python\Python311\Lib\site-packages\sklearn\base.py:413: UserWarning: X has feature names, but LinearRegression was fitted without feature names
  warnings.warn(


Size(m2)  Predict_Price
0      1000  325091.344396
1      2000  548270.086990